version: '3.3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mona-backend

  backend:
    build: microservices/backend
    ports:
      - 3000:3000
    networks:
      - mona-backend
  
networks:
  mona-backend: