service: mona-test

provider:
    name: aws
    runtime: nodejs8.10

functions:
    debug:
        handler: index.debug
        events:
            - http: POST debug

    museums_create:
        handler: controllers/museums.create
        events:
            - http:
                  path: museums
                  method: post

    museums_get:
        handler: controllers/museums.get
        events:
            - http:
                  path: museums
                  method: get

    exhibitions_create:
        handler: controllers/exhibitions.create
        events:
            - http:
                  path: exhibitions
                  method: post

    exhibitions_get:
        handler: controllers/exhibitions.get
        events:
            - http:
                  path: exhibitions
                  method: get

    exhibitions_update:
        handler: controllers/exhibitions.update
        events:
            - http:
                  path: exhibitions
                  method: patch

    artworks_create:
        handler: controllers/artworks.create
        events:
            - http:
                  path: artworks
                  method: post

    artworks_get:
        handler: controllers/artworks.get
        events:
            - http:
                  path: artworks
                  method: get

    artworks_update:
        handler: controllers/artworks.update
        events:
            - http:
                  path: artworks
                  method: patch

plugins:
    - serverless-offline
